### ISSUE TITLE
Pass object as value

### ISSUE THREAD

**Issue by xrei** [wan2land/vue-scroll-picker#10]
When passing options value like this `:options="[{value: {a: 1}}, {value: {a: 2}}]"` it won't work because of you compare objects and it always will return false.
[here](https://github.com/wan2land/vue-scroll-picker/blob/master/src/picker/picker.js#L31)
 [and here](https://github.com/wan2land/vue-scroll-picker/blob/master/src/picker/picker.js#L110)
[also here](https://github.com/wan2land/vue-scroll-picker/blob/master/src/picker/picker.js#L268) Vue will warn about using key as non-primitive value.

This could be solved by explicitly passing an `id` to options array when value is object or generating `id`'s

**Comment by wan2land** [comment]
It seems that this problem can be solved by creating Options with the IDs of the suggested options(`[{ a: 1 }, { a: 2 }]`).

```vue
<template>
  <scroll-picker :options="options" v-model="data" />
</template>
<script>
export default {
  data() {
    const customOptions = [
      {a: 1},
      {a: 2},
    ]
    return {
      data: null,
      customOptions,
      options: customOptions.map(option => ({  value: option.a, name: `option ${option.a}` })),
    }
  },
  computed: {
    selectedCustomOption() {
      return this.customOptions.find(option => option.a === this.data)
    },
  },
}
</script>
```

I don't want the library itself to be complicated because of the features I don't use much.

I don't know the exact situation, so there may be parts I don't know. If you tell me more, I will think about it.
