### ISSUE TITLE
New feature : iOS Style

### ISSUE THREAD

**Issue by vykimo** [wan2land/vue-scroll-picker#355]
Hi,
I noticed that on iOS style it looks like more curvy :
![iosstyle](https://user-images.githubusercontent.com/15012658/130067564-5be038a3-161c-4cb8-a38d-626c612d9643.png)
Ref: https://v0-17.quasar-framework.org/components/datetime-picker.html

Can you add this kind of "iOS style". You could add the **ios-style** props for your component.
Here are the possible rotation in order to make it look like this : 
```
  transform: rotateX(54deg);
  transform: rotateX(36deg);
  transform: rotateX(18deg);
transform: rotateX(0deg); (selected option)
  transform: rotateX(-18deg);
  transform: rotateX(-36deg);
  transform: rotateX(-54deg);
```
What do you think ?
Btw I love your component 👍

**Comment by wan2land** [comment]
Thank you PR. :-)

When a new option is added before an existing option, the position of the rotator is calculated based on 2D. (see example `Dynamic Options`)
If you change this component to 3D, need a completely different calculation formula. (sin, cos, blabla..) I want it to be a minimal package that only works with the necessary functions. If you want to control this as an option, I think it is better to create a new component(or package) because the complexity of the component increases.

Perhaps you can refer to the following link.
https://github.com/quasarframework/quasar/blob/v0.17/src/components/datetime/QDatetimePicker.ios.js
